# Dockerfile pour le Front-End
FROM node:14-alpine

# Créer un répertoire de travail
WORKDIR /app

# Exposer le port par défaut de l'application
EXPOSE 8085

# CMD ["npm", "run", "serve"] <- Commenter cette ligne pour l'instant

