version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8085:8085"
    depends_on:
      - backend
    networks:
      - frontend-backend-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - frontend-backend-net
      - backend-db-net

  db:
    build: ./database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: wishlist
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-db-net
      - db-script-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wishlist -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  script:
    build: ./insertion_script
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-script-net

networks:
  frontend-backend-net:
    driver: bridge
  backend-db-net:
    driver: bridge
  db-script-net:
    driver: bridge

